# Generated by Django 4.1.2 on 2023-01-18 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BanglaDistrictName', models.CharField(blank=True, max_length=200, null=True)),
                ('EnglishDistrictName', models.CharField(blank=True, max_length=200, null=True)),
                ('lat', models.CharField(blank=True, max_length=200, null=True)),
                ('long', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BanglaDivisionName', models.CharField(blank=True, max_length=200, null=True)),
                ('EnglishDivisionName', models.CharField(blank=True, max_length=200, null=True)),
                ('lat', models.CharField(blank=True, max_length=200, null=True)),
                ('long', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Upazila',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BanglaUpazilaName', models.CharField(blank=True, max_length=200, null=True)),
                ('EnglishUpazilaName', models.CharField(blank=True, max_length=200, null=True)),
                ('District', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Address.district')),
            ],
        ),
        migrations.CreateModel(
            name='PostCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PostOffice', models.CharField(max_length=200)),
                ('PostCode', models.IntegerField(blank=True, null=True)),
                ('District', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Address.district')),
                ('Division', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Address.division')),
            ],
        ),
        migrations.AddField(
            model_name='district',
            name='Division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Address.division'),
        ),
    ]
